In [1]:
import pandas as pd
from sklearn.datasets import make_classification

In [2]:
data = make_classification(n_samples=1000, n_features=10,n_classes=2, random_state=10)

In [3]:
x,y=data

In [4]:
x[0]

array([-1.00583777, -0.37653943, -0.62017967, -0.15756653, -1.12080531,
       -0.58909086, -1.57457766,  1.67804613,  1.0801799 ,  0.35358714])

In [5]:
y[0]

np.int64(0)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [8]:
len(x_train)

750

In [9]:
len(x_test)

250

In [11]:
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred= model.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [13]:
confusion_matrix(y_pred, y_test)

array([[108,  12],
       [ 24, 106]])

In [15]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86       120
           1       0.90      0.82      0.85       130

    accuracy                           0.86       250
   macro avg       0.86      0.86      0.86       250
weighted avg       0.86      0.86      0.86       250



In [16]:
accuracy_score(y_pred, y_test)

0.856

In [17]:
x1,y1=make_classification(n_samples=10,n_classes=2,n_features=10)

In [18]:
y1_pred= model.predict(x1)

In [19]:
y1

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

In [20]:
accuracy_score(y1,y1_pred)

0.8

In [21]:
x1

array([[-0.48232379,  0.0641197 , -1.07568398,  0.10974719, -0.32841666,
         0.68940612, -1.81174928, -0.18837688, -0.00982618,  0.33672384],
       [-0.40261572,  1.97062847,  0.75501887, -0.88669487,  0.64383442,
         0.0661783 ,  1.2402617 ,  0.30896209,  0.11765326, -0.12191558],
       [ 1.11731018, -0.41453419, -2.07929   , -0.14922621,  1.68997204,
         2.03372354, -1.26122124, -2.88718315,  0.78211001,  2.09287952],
       [-0.8902744 ,  0.66214762,  0.51773216,  0.11641236,  0.24850152,
        -0.83527126, -0.43380906,  1.58174186,  0.17128218, -1.04630061],
       [-0.55977292,  0.20935407,  0.4336432 , -0.14047741,  1.13940232,
         0.70626682,  0.87164203, -0.13272428, -0.69627014,  0.31653977],
       [ 1.13308317,  0.09561898,  0.50442272,  0.23315754,  1.70922102,
         1.32534533,  0.98147707, -2.25321512, -1.55349511,  1.53918734],
       [ 2.00364293,  0.97904294,  0.31227375, -0.14817027,  0.12114531,
        -1.76241954,  0.21332096, -0.2257375 

In [22]:
x[1]

array([ 0.41117999,  0.76240872, -0.78421   , -0.09647917, -0.40875846,
       -0.66578006,  0.21094182, -0.85044853, -0.46130068,  1.06223729])